version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: my-library
      PGDATA: /usr/src/app/data/pgdata
    ports:
    - "5433:5432"
    volumes:
    - data:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    ports:
     - "8080:8080"
    volumes:
     - .:/usr/src/app/my-library
volumes:
  data:

